framework:
    cache:
        prefix_seed: 'jf'

        # Cache par défaut
        app: cache.adapter.filesystem
        system: cache.adapter.system

        # Pools de cache personnalisés avec une durée de vie par défaut
        pools:
            my.dedicated.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # Durée de vie par défaut de 3600 secondes pour ce pool spécifique
