# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    filter_sets:
        cache: ~

        100x100:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
            format: webp
        
        187x288:
            quality: 100
            filters:
                thumbnail: { size: [187, 288], mode: outbound }
            format: webp
        
        600x490:
            quality: 100
            filters:
                thumbnail: { size: [600, 490], mode: outbound }
            format: webp

        300x200:
            quality: 100
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
            format: webp

        300x436:
            quality: 100
            filters:
                thumbnail: { size: [300, 436], mode: outbound }
            format: webp

