# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    filter_sets:
        cache: ~

        100x100:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
            format: webp
        
        288x187:
            quality: 100
            filters:
                thumbnail: { size: [288, 187], mode: outbound }
            format: webp
        
        600x490:
            quality: 100
            filters:
                thumbnail: { size: [600, 490], mode: outbound }
            format: webp

        300x200:
            quality: 100
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
            format: webp

        300x436:
            quality: 100
            filters:
                thumbnail: { size: [300, 436], mode: outbound }
            format: webp
        
        896x500:
            quality: 100
            filters:
                thumbnail: { size: [896, 500], mode: outbound }
            format: webp
            
        436x300:
            quality: 100
            filters:
                thumbnail: { size: [436, 300], mode: outbound }
            format: webp

        80x80:
            quality: 100
            filters:
                thumbnail: { size: [80, 80], mode: outbound }
            format: webp

